language: node_js
env:
  - TEST_COMMAND=./travis.sh TEST_SETTINGS=polltable
  - TEST_COMMAND=./travis.sh TEST_SETTINGS=binlog-5.1
  - TEST_COMMAND=./travis.sh TEST_SETTINGS=binlog-5.5
  - TEST_COMMAND=./travis.sh TEST_SETTINGS=binlog-5.6
node_js:
  - "0.10"
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
before_script:
  - sudo apt-get install libaio1 libaio-dev
  - ./test/travis/install.sh
  - mysql -h 127.0.0.1 -P3351 -uroot -e 'create database myapp_test;'
  - mysql -h 127.0.0.1 -P3355 -uroot -e 'create database myapp_test;'
  - mysql -h 127.0.0.1 -P3356 -uroot -e 'create database myapp_test;'
after_script:
  - kill $(cat mysql-5.1.73-linux-x86_64-glibc23/mysql.pid)
  - kill $(cat mysql-5.5.41-linux2.6-x86_64/mysql.pid)
  - kill $(cat mysql-5.6.22-linux-glibc2.5-x86_64/mysql.pid)
